import Rohit from "../assets/RohitY.jpg";
import Parth from "../assets/Parth.jpg";
import Ankur from "../assets/Ankur.jpg";
import Vivek from "../assets/Vivek.jpg";
import Neeraj from "../assets/Neeraj.jpg";
import Aryan from "../assets/Aryan.jpg";
import Pratik from "../assets/Pratik.jpg";
import Pranav from "../assets/Pranav.jpg";
import Chaitanya from "../assets/Chaitanya.jpg";
import Hitanshu from "../assets/Hitanshu.jpg";
import RohitKhandekar from "../assets/RohitKhandekar.jpg";
import Jyoti from "../assets/Jyoti.jpg";
import Akshay from "../assets/Akshay.jpg";
import Rhythm from "../assets/Rhythm.jpg";
import Pavan from "../assets/Pavan.jpg";
import Dhriti from "../assets/Dhriti.jpg";
import Parshwa from "../assets/Parshwa.jpg";
import Sahil from "../assets/Sahil.jpg";
import Sheetal from "../assets/Sheetal.jpg";
import Pranjal from "../assets/Pranjal.jpg";
import Aditya from "../assets/Aditya.jpg";
import Taher from "../assets/Taher.jpg";

export const teams = [
  {
    fname: "Rohit",
    lname: "Yadav",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Crown-GS",
    project3: "na",
    domain: "Embedded",
    departmentclg: "Information technology",
    about:
      "I explored the embedded domain and got to learn a lot about dataset, live experiments, practical learning",
    linkedin:
      "https://www.linkedin.com/in/rohit-yadav-3253b9239?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "rohit15@somaiya.edu",
    profile: Rohit,
  },
  {
    fname: "Parth",
    lname: "Pulkundwar",
    yearleft: 0,
    active: true,
    project1: "Avruti",
    project2: "Beliefsat-0",
    project3: "UASS",
    domain: "Data Science",
    departmentclg: "Computer Engineering",
    about:
      "NLL provides us the right mixture of hardworking yet fun team-mates, which collaborate on challenging projects.",
    linkedin: "https://www.linkedin.com/in/parth-pulkundwar-79914a289/",
    email: "p.pulkundwar@somaiya.edu",
    profile: Parth,
  },
  {
    fname: "Ankur",
    lname: "Chheda",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Beliefsat-1",
    project3: "Crown-GS",
    domain: "Software",
    departmentclg: "Information Technology",
    about:
      "Joining NLL lab has been an enriching journey. Learned HTML, CSS, JavaScript, Python, and React.js. Helped in developing a website from scratch, gaining practical project experience. Immersed in real-world coding challenges and collaborative learning. Enhanced proficiency in diverse programming languages. NLL lab provided a dynamic space for hands-on exploration.",
    linkedin: "https://in.linkedin.com/in/ankur-chheda-66b5992a6",
    email: "ankur.chheda@somaiya.edu",
    profile: Ankur,
  },
  {
    fname: "Vivek",
    lname: "Dhanawade",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Beliefsat-1",
    project3: "Crown-GS",
    domain: "Radio Frequency",
    departmentclg: "Artificial Intelligence and Data Science",
    about:
      "Get to learn about problem solving approach, team building, management and industry and space level technologies",
    linkedin:
      "https://www.linkedin.com/in/vivek-dhanawade-47483b2a6?trk=contact-info",
    email: "vivek.dhanawade@somaiya.edu",
    profile: Vivek,
  },
  {
    fname: "Neeraj",
    lname: "Patil",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Beliefsat-1",
    project3: "UASS",
    domain: "PCB Design",
    departmentclg: "EXTC",
    about: "I am PCB domain Head of new leap labs",
    linkedin:
      "https://www.linkedin.com/in/neeraj-patil-78220725a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "neeraj.rp@somaiya.edu",
    profile: Neeraj,
  },
  {
    fname: "Aryan",
    lname: "Ilake",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Crown-GS",
    project3: "na",
    domain: "Software",
    departmentclg: "AI-DS",
    about:
      "My experience is pretty good while working with other team members in NLL. Have learned many things after joining NLL.",
    linkedin: "https://www.linkedin.com/in/aryan-ilake-04bb042a6/",
    email: "aryan.ilake@somaiya.edu",
    profile: Aryan,
  },
  {
    fname: "Pratik",
    lname: "Gangapurwala",
    yearleft: 2022,
    active: false,
    project1: "Somaiya-Pod",
    project2: "Beliefsat-1",
    project3: "na",
    domain: "Structure Design",
    departmentclg: "Electronics and Telecommunication",
    about:
      "I joined New Leap Labs in my first year, in the course of 2 years of NLL I had provided me confidence in my hardware and software technical skills as well as have helped me learn team management skills. I can certify that whatever I am today a substantial credit for it goes to NLL in shaping me.",
    linkedin: "https://www.linkedin.com/in/pratik-gangapurwala-6aa3321a8",
    email: "pgangapurwala@gmail.com",
    profile: Pratik,
  },
  {
    fname: "Pranav",
    lname: "Narkhede",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Crown-GS",
    project3: "na",
    domain: "Radio Frequency",
    departmentclg: "AI-DS",
    about: "Fun",
    linkedin:
      "https://www.linkedin.com/in/pranav-narkhede-0793a3261?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "pranav.narkhede@somaiya.edu",
    profile: Pranav,
  },
  {
    fname: "Chaitanya",
    lname: "Kasambe",
    yearleft: 2020,
    active: true,
    project1: "Beliefsat-1",
    project2: "UASS",
    project3: "Beliefsat-0",
    domain: "Embedded",
    departmentclg: "Electronics and Telecommunication",
    about:
      "I joined the core team in the 2nd year of NLL formation. I initially worked on UASS project, became R&D head of the team. I have worked on beliefsat0. After starting work at Dhruva Space, I am mentoring the team for various projects, mainly on how to qualify the subsystems for space.",
    linkedin: "https://www.linkedin.com/in/cakasambe/",
    email: "c.kasambe@somaiya.edu",
    profile: Chaitanya,
  },
  {
    fname: "Hitanshu",
    lname: "Kanabar",
    yearleft: 0,
    active: false,
    project1: "Beliefsat-0",
    project2: "Beliefsat-1",
    project3: "UASS",
    domain: "Structure Design",
    departmentclg: "Information technology",
    about:
      "So, I am Hitanshu from 2nd year in IT department. I joined NLI (New Leap Initiative) since @ years ago, as a Structure Design. I done all tools regarding my domain in few weeks. After that, I got some tasks from my seniors, and I did them very well. I like my work, and all people are very great in NLL.",
    linkedin: "https://www.linkedin.com/in/hitanshu-kanabar-b69a63298/",
    email: "hitanshu.k@somaiya.edu",
    profile: Hitanshu,
  },
  {
    fname: "Rohit",
    lname: "Khandekar",
    yearleft: 2020,
    active: true,
    project1: "UASS",
    project2: "na",
    project3: "na",
    domain: "Hardware",
    departmentclg: "Information technology",
    about:
      "My name is Rohit Khandekar, and I was part of UASS (Upper Air Sounding System) project under NLL. We built a weather detecting device in collaboration with Databyte services and systems for IMD (Indian Meteorological Department). We successfully built a working prototype which measured pressure, temperature, and humidity. We had several launches at IMD along with their weather detecting device, named Radiosonde, to compare how accurate our prototype was. After 6-7 launches, we got almost accurate values. I am really blessed to be part of NLL.",
    linkedin: "https://www.linkedin.com/in/rohit-khandekar-111755168/",
    email: "rohit.khandekar@somaiya.edu",
    profile: RohitKhandekar,
  },
  {
    fname: "Jyoti",
    lname: "Gadgil",
    yearleft: 2022,
    active: false,
    project1: "Beliefsat-0",
    project2: "Beliefsat-1",
    project3: "na",
    domain: "Hardware",
    departmentclg: "Electronics and Telecommunication",
    about:
      "From 2018 to 2022, I had the privilege of contributing to New Leap Labs, specifically working on the BeliefSat project. Throughout my tenure, I not only acquired new skills but also gained valuable managerial experience. Being a part of this dynamic team was an honor, providing me with opportunities to broaden my knowledge and make meaningful contributions.",
    linkedin: "http://www.linkedin.com/in/jyoti-gadgil",
    email: "jyoti.gadgil@somaiya.edu",
    profile: Jyoti,
  },
  {
    fname: "Akshay",
    lname: "Jain",
    yearleft: 2020,
    active: true,
    project1: "Beliefsat-0",
    project2: "na",
    project3: "na",
    domain: "Radio Frequency",
    departmentclg: "EXTC",
    about:
      "Played a crucial role in the development of the CROWN ham club and am a co-founding member. Had a substantial contribution to the team by making various GS antennae. We were determined to launch the satellite even when no one believed us, and we succeeded because #Webelieve.",
    linkedin: "https://www.linkedin.com/in/akshay-jain-966073162/",
    email: "akshay.hj30@gmail.com",
    profile: Akshay,
  },
  {
    fname: "Rhythm",
    lname: "Bhatt",
    yearleft: 2022,
    active: true,
    project1: "Beliefsat-1",
    project2: "Somaiya-Pod",
    project3: "na",
    domain: "Non Technical",
    departmentclg: "Computer Engineering",
    about:
      "- Started as a Product Trainee in May 2020. \n- Learned Fusion 360, and Eagle during my training. \n- Worked on V2 of Somaiya POD. \n- Fabricated POD and did Functional Testing. \n- Meeting with Dcubed. \n- Promoted to Project Manager. \n- Worked on PCB Testing. \n- Started working on V3 of PCBs of Beliefsat-1. \n- Initiated weekly Knowledge Transfer sessions. \n- Put NLI to a social media front. \n- Conducted 'Expert Talk on Propulsion Engineering and Space Technology' by Ishita Ranade.",
    linkedin: "https://www.linkedin.com/in/rhythmbhatt/",
    email: "rhythm.bhatt@somaiya.edu",
    profile: Rhythm,
  },
  {
    fname: "Pavan",
    lname: "Jangam",
    yearleft: 2023,
    active: true,
    project1: "UASS",
    project2: "Crown-GS",
    project3: "Beliefsat-0",
    domain: "Radio Frequency",
    departmentclg: "EXTC",
    about:
      "I have been part of the team since 2019, gaining experience in RF and Embedded systems. I had the opportunity to lead the team for one year. The team is motivated toward set goals and will achieve great heights in the near future.",
    linkedin:
      "https://www.linkedin.com/in/pavan-jangam-9732791a6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    email: "pavan.jangam@somaiya.edu",
    profile: Pavan,
  },
  {
    fname: "Dhriti",
    lname: "Kothari",
    yearleft: 0,
    active: true,
    project1: "UASS",
    project2: "na",
    project3: "na",
    domain: "Embedded",
    departmentclg: "Computer Engineering",
    about:
      "In a short span of time of having joined NLL, I have learned so many different things and tried my hands on many new things. NLL gives me an opportunity to explore new fields of my interest.",
    linkedin: "http://linkedin.com/in/dhriti-kothari-9b922525b",
    email: "dhriti.m@somaiya.edu",
    profile: Dhriti,
  },
  {
    fname: "Parshwa",
    lname: "Dama",
    yearleft: 0,
    active: false,
    project1: "Somaiya-Pod",
    project2: "Crown-GS",
    project3: "na",
    domain: "Hardware",
    departmentclg: "EXTC",
    about:
      "My experience in NLL was one of the best learning phases during my academic years. Initially, I was part of the communication subsystem, then I worked on rocketry. I even visited WPC with Saikumar regarding the Amateur radio license, and I learned a lot. I had a great time working here and created a lot of memories.",
    linkedin: "https://www.linkedin.com/in/parshwadama",
    email: "parshwadama12@gmail.com",
    profile: Parshwa,
  },
  {
    fname: "Sahil",
    lname: "Mange",
    yearleft: 0,
    active: true,
    project1: "UASS",
    project2: "Crown-GS",
    project3: "Beliefsat-0",
    domain: "Embedded",
    departmentclg: "Information technology",
    about:
      "I am Sahil Mange, studying second year engineering at KJSIT. I joined NLL on the first day and have learned much about IOT and embedded systems. NLL gives me the opportunity to explore my interest in space technologies.",
    linkedin: "https://www.linkedin.com/in/sahil-mange-7b74722a8/",
    email: "sahil.mange@somaiya.edu",
    profile: Sahil,
  },

  {
    fname: "Sheetal",
    lname: "Popat",
    yearleft: 2024,
    active: false,
    project1: "Beliefsat-0",
    project2: "UASS",
    project3: "Avruti",
    domain: "Embedded",
    departmentclg: "Computer Engineering",
    about: "",
    linkedin:
      "https://www.linkedin.com/in/sheetal-popat-705619222/?originalSubdomain=in",
    email: "sheetal.popat@somaiya.edu",
    profile: Sheetal,
  },
  {
    fname: "Pranjal",
    lname: "Sancheti",
    yearleft: 0,
    active: false,
    project1: "Beliefsat-0",
    project2: "UASS",
    project3: "na",
    domain: "Software",
    departmentclg: "Computer Engineering",
    about: "",
    linkedin:
      "https://www.linkedin.com/in/pranjalsancheti/?originalSubdomain=in",
    email: "pranjal.sancheti@somaiya.edu",
    profile: Pranjal,
  },
  {
    fname: "Aditya",
    lname: "Singh",
    yearleft: 0,
    active: true,
    project1: "Beliefsat-0",
    project2: "Crown-GS",
    project3: "na",
    domain: "Embedded",
    departmentclg: "EXTC",
    about: "",
    linkedin: "",
    email: "ass28@somaiya.edu",
    profile: Aditya,
  },
  {
    fname: "Taher",
    lname: "Stovewala",
    yearleft: 0,
    active: false,
    project1: "Beliefsat-0",
    project2: "na",
    project3: "na",
    domain: "Embedded",
    departmentclg: "EXTC",
    about: "",
    linkedin: "https://www.linkedin.com/in/taher-stovewala-104304307/",
    email: "taher.s@somaiya.edu",
    profile: Taher,
  },
];
