version: "3.8"

services:
  app:
    container_name: admin-nll-frontend
    image: admin-nll
    build:
      context: .
    ports:
        - 80:80
    environment:
        REACT_APP_SERVER_DOMAIN: 'http://localhost:8080'
        
